# Generated by Django 4.0 on 2022-01-07 08:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OnePairArbitrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField(unique=True)),
                ('precent', models.FloatField()),
                ('baseFrom', models.CharField(max_length=42)),
                ('targetFrom', models.CharField(max_length=42)),
                ('baseTo', models.CharField(max_length=42)),
                ('targetTo', models.CharField(max_length=42)),
                ('convertedPriceFrom', models.FloatField()),
                ('convertedPriceTo', models.FloatField()),
                ('volume', models.FloatField()),
                ('marketFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketFrom', to='mainApp.market')),
                ('marketTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketTo', to='mainApp.market')),
                ('platforms', models.ManyToManyField(to='mainApp.Platform')),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
