# Generated by Django 4.0 on 2022-01-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('symbol', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OnePairArbitrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.FloatField()),
                ('convertedPriceFrom', models.FloatField()),
                ('convertedPriceTo', models.FloatField()),
                ('volume', models.FloatField()),
                ('baseFrom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseFrom', to='mainApp.coin')),
                ('baseTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseTo', to='mainApp.coin')),
                ('marketFrom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketFrom', to='mainApp.market')),
                ('marketTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketTo', to='mainApp.market')),
                ('targetFrom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targetFrom', to='mainApp.coin')),
                ('targetTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='targetTo', to='mainApp.coin')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='platforms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.platform'),
        ),
    ]
